<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\TouristAttraction;

class TouristAttractionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $attractions = [
            // 1-10: Monumentos Icons
            [
                'cidade' => 'Rio de Janeiro',
                'pais' => 'Brasil',
                'categoria' => 'Histórico',
                'imagem_url' => 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800',
                'endereco' => 'Parque Nacional da Tijuca, Alto da Boa Vista, Rio de Janeiro - RJ',
                'nome_pt' => 'Cristo Redentor',
                'nome_en' => 'Christ the Redeemer',
                'nome_es' => 'Cristo Redentor',
                'descricao_pt' => 'O Cristo Redentor é uma estátua art déco de Jesus Cristo, localizada no topo do morro do Corcovado, a 709 metros acima do nível do mar, no Parque Nacional da Tijuca, com vista para a maior parte da cidade do Rio de Janeiro.',
                'descricao_en' => 'Christ the Redeemer is an Art Deco statue of Jesus Christ, located at the top of Corcovado mountain, 709 meters above sea level, in Tijuca National Park, overlooking most of the city of Rio de Janeiro.',
                'descricao_es' => 'El Cristo Redentor es una estatua art déco de Jesucristo, ubicada en la cima del monte Corcovado, a 709 metros sobre el nivel del mar, en el Parque Nacional de Tijuca, con vista a la mayor parte de la ciudad de Río de Janeiro.',
            ],
            [
                'cidade' => 'Paris',
                'pais' => 'França',
                'categoria' => 'Arquitetônico',
                'imagem_url' => 'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?w=800',
                'endereco' => 'Champ de Mars, 5 Avenue Anatole France, 75007 Paris, França',
                'nome_pt' => 'Torre Eiffel',
                'nome_en' => 'Eiffel Tower',
                'nome_es' => 'Torre Eiffel',
                'descricao_pt' => 'A Torre Eiffel é uma torre treliçada de ferro forjado localizada no Champ de Mars, em Paris, França. Construída de 1887 a 1889, foi projetada pelo engenheiro Gustave Eiffel.',
                'descricao_en' => 'The Eiffel Tower is a wrought-iron lattice tower located on the Champ de Mars in Paris, France. Built from 1887 to 1889, it was designed by engineer Gustave Eiffel.',
                'descricao_es' => 'La Torre Eiffel es una torre de celosía de hierro forjado ubicada en el Champ de Mars en París, Francia. Construida de 1887 a 1889, fue diseñada por el ingeniero Gustave Eiffel.',
            ],
            [
                'cidade' => 'Agra',
                'pais' => 'Índia',
                'categoria' => 'Religioso',
                'imagem_url' => 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800',
                'endereco' => 'Taj Mahal, Agra, Uttar Pradesh 282001, Índia',
                'nome_pt' => 'Taj Mahal',
                'nome_en' => 'Taj Mahal',
                'nome_es' => 'Taj Mahal',
                'descricao_pt' => 'O Taj Mahal é um mausoléu de mármore branco marfim, localizado na cidade de Agra, na Índia. Foi construído pelo imperador mogol Shah Jahan em memória de sua esposa favorita, Mumtaz Mahal.',
                'descricao_en' => 'The Taj Mahal is an ivory-white marble mausoleum, located in the city of Agra, India. It was built by the Mughal emperor Shah Jahan in memory of his favorite wife, Mumtaz Mahal.',
                'descricao_es' => 'El Taj Mahal es un mausoleo de mármol blanco marfil, ubicado en la ciudad de Agra, India. Fue construido por el emperador mogol Shah Jahan en memoria de su esposa favorita, Mumtaz Mahal.',
            ],
            [
                'cidade' => 'Nova York',
                'pais' => 'Estados Unidos',
                'categoria' => 'Arquitetônico',
                'imagem_url' => 'https://images.unsplash.com/photo-1502602898534-0df0b3f3d3b1?w=800',
                'endereco' => 'Liberty Island, Nova York, NY 10004, Estados Unidos',
                'nome_pt' => 'Estátua da Liberdade',
                'nome_en' => 'Statue of Liberty',
                'nome_es' => 'Estatua de la Libertad',
                'descricao_pt' => 'A Estátua da Liberdade é uma escultura neoclássica colossal localizada na Ilha da Liberdade no porto de Nova York. Foi um presente dos franceses aos americanos em 1886.',
                'descricao_en' => 'The Statue of Liberty is a colossal neoclassical sculpture located on Liberty Island in New York Harbor. It was a gift from the French to the Americans in 1886.',
                'descricao_es' => 'La Estatua de la Libertad es una escultura neoclásica colosal ubicada en la Isla de la Libertad en el puerto de Nueva York. Fue un regalo de los franceses a los estadounidenses en 1886.',
            ],
            [
                'cidade' => 'Sydney',
                'pais' => 'Austrália',
                'categoria' => 'Arquitetônico',
                'imagem_url' => 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800',
                'endereco' => 'Bennelong Point, Sydney NSW 2000, Austrália',
                'nome_pt' => 'Casa da Ópera de Sydney',
                'nome_en' => 'Sydney Opera House',
                'nome_es' => 'Casa de la Ópera de Sídney',
                'descricao_pt' => 'A Casa da Ópera de Sydney é um centro de artes cênicas multivenue em Sydney, Austrália. É um dos edifícios mais famosos e distintos do século XX.',
                'descricao_en' => 'The Sydney Opera House is a multi-venue performing arts centre in Sydney, Australia. It is one of the most famous and distinctive buildings of the 20th century.',
                'descricao_es' => 'La Casa de la Ópera de Sídney es un centro de artes escénicas multivenue en Sídney, Australia. Es uno de los edificios más famosos y distintivos del siglo XX.',
            ],
            [
                'cidade' => 'Roma',
                'pais' => 'Itália',
                'categoria' => 'Histórico',
                'imagem_url' => 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800',
                'endereco' => 'Piazza del Colosseo, 1, 00184 Roma RM, Itália',
                'nome_pt' => 'Coliseu',
                'nome_en' => 'Colosseum',
                'nome_es' => 'Coliseo',
                'descricao_pt' => 'O Coliseu é um anfiteatro oval localizado no centro da cidade de Roma, Itália. Construído de tijolo e pedra, é o maior anfiteatro do mundo e um dos maiores exemplos da arquitetura romana.',
                'descricao_en' => 'The Colosseum is an oval amphitheater located in the center of the city of Rome, Italy. Built of brick and stone, it is the largest amphitheater in the world and one of the greatest examples of Roman architecture.',
                'descricao_es' => 'El Coliseo es un anfiteatro ovalado ubicado en el centro de la ciudad de Roma, Italia. Construido de ladrillo y piedra, es el anfiteatro más grande del mundo y uno de los mayores ejemplos de la arquitectura romana.',
            ],
            [
                'cidade' => 'Londres',
                'pais' => 'Reino Unido',
                'categoria' => 'Arquitetônico',
                'imagem_url' => 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800',
                'endereco' => 'Westminster, Londres SW1A 0AA, Reino Unido',
                'nome_pt' => 'Big Ben',
                'nome_en' => 'Big Ben',
                'nome_es' => 'Big Ben',
                'descricao_pt' => 'Big Ben é o nome dado ao grande sino do relógio da torre norte do Palácio de Westminster, em Londres. É um dos símbolos mais reconhecidos do Reino Unido.',
                'descricao_en' => 'Big Ben is the name given to the great bell of the clock tower at the north end of the Palace of Westminster in London. It is one of the most recognized symbols of the United Kingdom.',
                'descricao_es' => 'Big Ben es el nombre dado a la gran campana de la torre del reloj en el extremo norte del Palacio de Westminster en Londres. Es uno de los símbolos más reconocidos del Reino Unido.',
            ],
            [
                'cidade' => 'Pequim',
                'pais' => 'China',
                'categoria' => 'Histórico',
                'imagem_url' => 'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=800',
                'endereco' => 'Great Wall of China, Pequim, China',
                'nome_pt' => 'Grande Muralha da China',
                'nome_en' => 'Great Wall of China',
                'nome_es' => 'Gran Muralla China',
                'descricao_pt' => 'A Grande Muralha da China é uma série de fortificações feitas de pedra, tijolo, terra batida, madeira e outros materiais, geralmente construída ao longo de uma linha leste-oeste através das fronteiras históricas do norte da China.',
                'descricao_en' => 'The Great Wall of China is a series of fortifications made of stone, brick, rammed earth, wood, and other materials, generally built along an east-to-west line across the historical northern borders of China.',
                'descricao_es' => 'La Gran Muralla China es una serie de fortificaciones hechas de piedra, ladrillo, tierra apisonada, madera y otros materiales, generalmente construida a lo largo de una línea este-oeste a través de las fronteras históricas del norte de China.',
            ],
            [
                'cidade' => 'Istambul',
                'pais' => 'Turquia',
                'categoria' => 'Religioso',
                'imagem_url' => 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800',
                'endereco' => 'Sultan Ahmet, Ayasofya Meydanı No:1, 34122 Fatih/İstanbul, Turquia',
                'nome_pt' => 'Hagia Sophia',
                'nome_en' => 'Hagia Sophia',
                'nome_es' => 'Hagia Sophia',
                'descricao_pt' => 'Hagia Sophia é uma antiga basílica ortodoxa grega, posteriormente uma mesquita imperial e agora um museu em Istambul, Turquia. É famosa por sua enorme cúpula.',
                'descricao_en' => 'Hagia Sophia is an ancient Greek Orthodox basilica, later an imperial mosque and now a museum in Istanbul, Turkey. It is famous for its massive dome.',
                'descricao_es' => 'Hagia Sophia es una antigua basílica ortodoxa griega, posteriormente una mezquita imperial y ahora un museo en Estambul, Turquía. Es famosa por su enorme cúpula.',
            ],
            [
                'cidade' => 'Veneza',
                'pais' => 'Itália',
                'categoria' => 'Cultural',
                'imagem_url' => 'https://images.unsplash.com/photo-1514896856000-91cb7886c5e8?w=800',
                'endereco' => 'Piazza San Marco, 30100 Venezia VE, Itália',
                'nome_pt' => 'Piazza San Marco',
                'nome_en' => 'St. Mark\'s Square',
                'nome_es' => 'Plaza de San Marcos',
                'descricao_pt' => 'A Piazza San Marco é a principal praça pública de Veneza, Itália, onde se encontra a Basílica de São Marcos. É conhecida como "a sala de estar da Europa".',
                'descricao_en' => 'St. Mark\'s Square is the main public square of Venice, Italy, where St. Mark\'s Basilica is located. It is known as "the drawing room of Europe".',
                'descricao_es' => 'La Plaza de San Marcos es la plaza pública principal de Venecia, Italia, donde se encuentra la Basílica de San Marcos. Es conocida como "el salón de Europa".',
            ],
            // 11-20: Maravilhas Naturais e Culturais
            [
                'cidade' => 'Cusco',
                'pais' => 'Peru',
                'categoria' => 'Histórico',
                'imagem_url' => 'https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=800',
                'endereco' => 'Machu Picchu, 08680, Peru',
                'nome_pt' => 'Machu Picchu',
                'nome_en' => 'Machu Picchu',
                'nome_es' => 'Machu Picchu',
                'descricao_pt' => 'Machu Picchu é uma cidade inca bem conservada, localizada no topo de uma montanha, a 2.400 metros de altitude, no vale do rio Urubamba, atual Peru.',
                'descricao_en' => 'Machu Picchu is a well-preserved Inca city, located on top of a mountain, 2,400 meters above sea level, in the Urubamba River valley, present-day Peru.',
                'descricao_es' => 'Machu Picchu es una ciudad inca bien conservada, ubicada en la cima de una montaña, a 2.400 metros sobre el nivel del mar, en el valle del río Urubamba, actual Perú.',
            ],
            [
                'cidade' => 'Ilha de Páscoa',
                'pais' => 'Chile',
                'categoria' => 'Cultural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Ilha de Páscoa, Valparaíso, Chile',
                'nome_pt' => 'Moai',
                'nome_en' => 'Moai',
                'nome_es' => 'Moai',
                'descricao_pt' => 'Os Moai são estátuas monolíticas humanas esculpidas pelos Rapa Nui na Ilha de Páscoa, no Chile, entre os anos 1250 e 1500. Representam os ancestrais deificados dos Rapa Nui.',
                'descricao_en' => 'The Moai are monolithic human figures carved by the Rapa Nui people on Easter Island, Chile, between the years 1250 and 1500. They represent the deified ancestors of the Rapa Nui.',
                'descricao_es' => 'Los Moai son figuras humanas monolíticas talladas por el pueblo Rapa Nui en la Isla de Pascua, Chile, entre los años 1250 y 1500. Representan a los ancestros deificados de los Rapa Nui.',
            ],
            [
                'cidade' => 'Honshu',
                'pais' => 'Japão',
                'categoria' => 'Natural',
                'imagem_url' => 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800',
                'endereco' => 'Monte Fuji, Honshu, Japão',
                'nome_pt' => 'Monte Fuji',
                'nome_en' => 'Mount Fuji',
                'nome_es' => 'Monte Fuji',
                'descricao_pt' => 'O Monte Fuji é a montanha mais alta da ilha de Honshu e de todo o arquipélago japonês, com 3.776 metros de altitude. É um vulcão ativo, embora tenha baixo risco de erupção.',
                'descricao_en' => 'Mount Fuji is the highest mountain on the island of Honshu and the entire Japanese archipelago, with an altitude of 3,776 meters. It is an active volcano, although it has a low risk of eruption.',
                'descricao_es' => 'El Monte Fuji es la montaña más alta de la isla de Honshu y de todo el archipiélago japonés, con una altitud de 3.776 metros. Es un volcán activo, aunque tiene un bajo riesgo de erupción.',
            ],
            [
                'cidade' => 'Petra',
                'pais' => 'Jordânia',
                'categoria' => 'Histórico',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Petra, Jordânia',
                'nome_pt' => 'Petra',
                'nome_en' => 'Petra',
                'nome_es' => 'Petra',
                'descricao_pt' => 'Petra é uma cidade histórica e arqueológica no sul da Jordânia, famosa por sua arquitetura esculpida em rocha e seu sistema de condutos de água. Foi a capital do reino nabateu.',
                'descricao_en' => 'Petra is a historical and archaeological city in southern Jordan, famous for its rock-cut architecture and water conduit system. It was the capital of the Nabataean Kingdom.',
                'descricao_es' => 'Petra es una ciudad histórica y arqueológica en el sur de Jordania, famosa por su arquitectura tallada en roca y su sistema de conductos de agua. Fue la capital del reino nabateo.',
            ],
            [
                'cidade' => 'Marrakech',
                'pais' => 'Marrocos',
                'categoria' => 'Cultural',
                'imagem_url' => 'https://upload.wikimedia.org/wikipedia/commons/7/7f/Maroc_Marrakech_Jemaa-el-Fna_Luc_Viatour.JPG',
                'endereco' => 'Jemaa el-Fnaa, Marrakech, Marrocos',
                'nome_pt' => 'Jemaa el-Fnaa',
                'nome_en' => 'Jemaa el-Fnaa',
                'nome_es' => 'Jemaa el-Fnaa',
                'descricao_pt' => 'Jemaa el-Fnaa é a principal praça e mercado de Marrakech, Marrocos. É um dos espaços públicos mais famosos do mundo árabe e um Patrimônio Cultural Imaterial da Humanidade.',
                'descricao_en' => 'Jemaa el-Fnaa is the main square and market in Marrakech, Morocco. It is one of the most famous public spaces in the Arab world and an Intangible Cultural Heritage of Humanity.',
                'descricao_es' => 'Jemaa el-Fnaa es la plaza principal y mercado de Marrakech, Marruecos. Es uno de los espacios públicos más famosos del mundo árabe y un Patrimonio Cultural Inmaterial de la Humanidad.',
            ],
            [
                'cidade' => 'Barcelona',
                'pais' => 'Espanha',
                'categoria' => 'Arquitetônico',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Carrer de Mallorca, 401, 08013 Barcelona, Espanha',
                'nome_pt' => 'Sagrada Família',
                'nome_en' => 'Sagrada Familia',
                'nome_es' => 'Sagrada Familia',
                'descricao_pt' => 'A Basílica da Sagrada Família é uma igreja católica romana projetada pelo arquiteto catalão Antoni Gaudí. É um dos exemplos mais conhecidos da arquitetura modernista catalã.',
                'descricao_en' => 'The Basilica of the Sagrada Familia is a Roman Catholic church designed by Catalan architect Antoni Gaudí. It is one of the best-known examples of Catalan modernist architecture.',
                'descricao_es' => 'La Basílica de la Sagrada Familia es una iglesia católica romana diseñada por el arquitecto catalán Antoni Gaudí. Es uno de los ejemplos más conocidos de la arquitectura modernista catalana.',
            ],
            [
                'cidade' => 'Amsterdã',
                'pais' => 'Países Baixos',
                'categoria' => 'Cultural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Museumstraat 1, 1071 XX Amsterdam, Países Baixos',
                'nome_pt' => 'Museu Van Gogh',
                'nome_en' => 'Van Gogh Museum',
                'nome_es' => 'Museo Van Gogh',
                'descricao_pt' => 'O Museu Van Gogh é um museu de arte dedicado às obras do pintor holandês Vincent van Gogh e seus contemporâneos. É um dos museus mais visitados da Holanda.',
                'descricao_en' => 'The Van Gogh Museum is an art museum dedicated to the works of Dutch painter Vincent van Gogh and his contemporaries. It is one of the most visited museums in the Netherlands.',
                'descricao_es' => 'El Museo Van Gogh es un museo de arte dedicado a las obras del pintor holandés Vincent van Gogh y sus contemporáneos. Es uno de los museos más visitados de los Países Bajos.',
            ],
            [
                'cidade' => 'Praga',
                'pais' => 'República Tcheca',
                'categoria' => 'Histórico',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Hradčany, 119 08 Praha 1, República Tcheca',
                'nome_pt' => 'Castelo de Praga',
                'nome_en' => 'Prague Castle',
                'nome_es' => 'Castillo de Praga',
                'descricao_pt' => 'O Castelo de Praga é um complexo de castelos em Praga, República Tcheca, que data do século IX. É a residência oficial do presidente da República Tcheca.',
                'descricao_en' => 'Prague Castle is a castle complex in Prague, Czech Republic, dating from the 9th century. It is the official residence of the President of the Czech Republic.',
                'descricao_es' => 'El Castillo de Praga es un complejo de castillos en Praga, República Checa, que data del siglo IX. Es la residencia oficial del Presidente de la República Checa.',
            ],
            [
                'cidade' => 'Budapeste',
                'pais' => 'Hungria',
                'categoria' => 'Arquitetônico',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Budapest, Széchenyi Lánchíd, 1051 Hungria',
                'nome_pt' => 'Ponte das Correntes',
                'nome_en' => 'Chain Bridge',
                'nome_es' => 'Puente de las Cadenas',
                'descricao_pt' => 'A Ponte das Correntes é uma ponte suspensa que atravessa o rio Danúbio entre Buda e Peste, as duas partes de Budapeste, Hungria. Foi a primeira ponte permanente sobre o Danúbio em Budapeste.',
                'descricao_en' => 'The Chain Bridge is a suspension bridge that spans the Danube River between Buda and Pest, the two parts of Budapest, Hungary. It was the first permanent bridge across the Danube in Budapest.',
                'descricao_es' => 'El Puente de las Cadenas es un puente colgante que cruza el río Danubio entre Buda y Pest, las dos partes de Budapest, Hungría. Fue el primer puente permanente sobre el Danubio en Budapest.',
            ],
            // 21-30: Destinos Asiáticos e Oceânicos
            [
                'cidade' => 'Tóquio',
                'pais' => 'Japão',
                'categoria' => 'Cultural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Shibuya, Tóquio, Japão',
                'nome_pt' => 'Cruzamento de Shibuya',
                'nome_en' => 'Shibuya Crossing',
                'nome_es' => 'Cruce de Shibuya',
                'descricao_pt' => 'O Cruzamento de Shibuya é um dos cruzamentos de pedestres mais movimentados do mundo, localizado em Tóquio, Japão. É um símbolo da vida urbana moderna do Japão.',
                'descricao_en' => 'Shibuya Crossing is one of the busiest pedestrian crossings in the world, located in Tokyo, Japan. It is a symbol of modern Japanese urban life.',
                'descricao_es' => 'El Cruce de Shibuya es uno de los cruces peatonales más concurridos del mundo, ubicado en Tokio, Japón. Es un símbolo de la vida urbana moderna japonesa.',
            ],
            [
                'cidade' => 'Seul',
                'pais' => 'Coreia do Sul',
                'categoria' => 'Arquitetônico',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Gangnam-gu, Seul, Coreia do Sul',
                'nome_pt' => 'Torre N Seoul',
                'nome_en' => 'N Seoul Tower',
                'nome_es' => 'Torre N Seoul',
                'descricao_pt' => 'A Torre N Seoul é uma torre de comunicação e observação localizada no topo do Monte Namsan em Seul, Coreia do Sul. É um dos marcos mais reconhecíveis da cidade.',
                'descricao_en' => 'N Seoul Tower is a communication and observation tower located on top of Mount Namsan in Seoul, South Korea. It is one of the most recognizable landmarks of the city.',
                'descricao_es' => 'La Torre N Seoul es una torre de comunicación y observación ubicada en la cima del Monte Namsan en Seúl, Corea del Sur. Es uno de los hitos más reconocibles de la ciudad.',
            ],
            [
                'cidade' => 'Bangkok',
                'pais' => 'Tailândia',
                'categoria' => 'Religioso',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Na Phra Lan Rd, Phra Nakhon, Bangkok 10200, Tailândia',
                'nome_pt' => 'Grande Palácio',
                'nome_en' => 'Grand Palace',
                'nome_es' => 'Gran Palacio',
                'descricao_pt' => 'O Grande Palácio é um complexo de edifícios no centro de Bangkok, Tailândia. É a residência oficial dos reis da Tailândia desde 1782.',
                'descricao_en' => 'The Grand Palace is a complex of buildings in the center of Bangkok, Thailand. It has been the official residence of the Kings of Thailand since 1782.',
                'descricao_es' => 'El Gran Palacio es un complejo de edificios en el centro de Bangkok, Tailandia. Ha sido la residencia oficial de los Reyes de Tailandia desde 1782.',
            ],
            [
                'cidade' => 'Singapura',
                'pais' => 'Singapura',
                'categoria' => 'Arquitetônico',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Marina Bay, Singapura',
                'nome_pt' => 'Marina Bay Sands',
                'nome_en' => 'Marina Bay Sands',
                'nome_es' => 'Marina Bay Sands',
                'descricao_pt' => 'Marina Bay Sands é um resort integrado em Singapura, conhecido por sua arquitetura icônica com três torres conectadas por um terraço no topo.',
                'descricao_en' => 'Marina Bay Sands is an integrated resort in Singapore, known for its iconic architecture with three towers connected by a rooftop terrace.',
                'descricao_es' => 'Marina Bay Sands es un resort integrado en Singapur, conocido por su arquitectura icónica con tres torres conectadas por una terraza en la azotea.',
            ],
            [
                'cidade' => 'Hong Kong',
                'pais' => 'China',
                'categoria' => 'Arquitetônico',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Victoria Peak, Hong Kong',
                'nome_pt' => 'Victoria Peak',
                'nome_en' => 'Victoria Peak',
                'nome_es' => 'Victoria Peak',
                'descricao_pt' => 'Victoria Peak é o pico mais alto da Ilha de Hong Kong, oferecendo vistas panorâmicas espetaculares da cidade e do porto de Victoria.',
                'descricao_en' => 'Victoria Peak is the highest peak on Hong Kong Island, offering spectacular panoramic views of the city and Victoria Harbour.',
                'descricao_es' => 'Victoria Peak es el pico más alto de la Isla de Hong Kong, ofreciendo vistas panorámicas espectaculares de la ciudad y el Puerto de Victoria.',
            ],
            [
                'cidade' => 'Melbourne',
                'pais' => 'Austrália',
                'categoria' => 'Cultural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Federation Square, Melbourne VIC 3000, Austrália',
                'nome_pt' => 'Federation Square',
                'nome_en' => 'Federation Square',
                'nome_es' => 'Federation Square',
                'descricao_pt' => 'Federation Square é um complexo cultural e cívico no centro de Melbourne, Austrália. É um dos espaços públicos mais importantes da cidade.',
                'descricao_en' => 'Federation Square is a cultural and civic complex in the center of Melbourne, Australia. It is one of the most important public spaces in the city.',
                'descricao_es' => 'Federation Square es un complejo cultural y cívico en el centro de Melbourne, Australia. Es uno de los espacios públicos más importantes de la ciudad.',
            ],
            [
                'cidade' => 'Auckland',
                'pais' => 'Nova Zelândia',
                'categoria' => 'Natural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Auckland, Nova Zelândia',
                'nome_pt' => 'Sky Tower',
                'nome_en' => 'Sky Tower',
                'nome_es' => 'Sky Tower',
                'descricao_pt' => 'A Sky Tower é uma torre de telecomunicações e observação em Auckland, Nova Zelândia. Com 328 metros de altura, é a estrutura mais alta do Hemisfério Sul.',
                'descricao_en' => 'The Sky Tower is a telecommunications and observation tower in Auckland, New Zealand. At 328 meters tall, it is the tallest structure in the Southern Hemisphere.',
                'descricao_es' => 'La Sky Tower es una torre de telecomunicaciones y observación en Auckland, Nueva Zelanda. Con 328 metros de altura, es la estructura más alta del Hemisferio Sur.',
            ],
            [
                'cidade' => 'Bali',
                'pais' => 'Indonésia',
                'categoria' => 'Cultural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Ubud, Bali, Indonésia',
                'nome_pt' => 'Templo de Tanah Lot',
                'nome_en' => 'Tanah Lot Temple',
                'nome_es' => 'Templo de Tanah Lot',
                'descricao_pt' => 'O Templo de Tanah Lot é um templo hindu balinês localizado em uma formação rochosa no mar. É um dos templos mais fotografados da Indonésia.',
                'descricao_en' => 'Tanah Lot Temple is a Balinese Hindu temple located on a rock formation in the sea. It is one of the most photographed temples in Indonesia.',
                'descricao_es' => 'El Templo de Tanah Lot es un templo hindú balinés ubicado en una formación rocosa en el mar. Es uno de los templos más fotografiados de Indonesia.',
            ],
            [
                'cidade' => 'Mumbai',
                'pais' => 'Índia',
                'categoria' => 'Arquitetônico',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Mumbai, Maharashtra, Índia',
                'nome_pt' => 'Portão da Índia',
                'nome_en' => 'Gateway of India',
                'nome_es' => 'Puerta de la India',
                'descricao_pt' => 'O Portão da Índia é um monumento histórico localizado em Mumbai, Índia. Foi construído para comemorar a visita do Rei George V e da Rainha Mary em 1911.',
                'descricao_en' => 'The Gateway of India is a historical monument located in Mumbai, India. It was built to commemorate the visit of King George V and Queen Mary in 1911.',
                'descricao_es' => 'La Puerta de la India es un monumento histórico ubicado en Mumbai, India. Fue construida para conmemorar la visita del Rey Jorge V y la Reina María en 1911.',
            ],
            // 31-40: Destinos Europeus e Africanos
            [
                'cidade' => 'Viena',
                'pais' => 'Áustria',
                'categoria' => 'Cultural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Schönbrunner Schloßstraße 47, 1130 Viena, Áustria',
                'nome_pt' => 'Palácio de Schönbrunn',
                'nome_en' => 'Schönbrunn Palace',
                'nome_es' => 'Palacio de Schönbrunn',
                'descricao_pt' => 'O Palácio de Schönbrunn é um palácio barroco em Viena, Áustria. Foi a residência de verão dos Habsburgos e é um dos monumentos culturais mais importantes da Áustria.',
                'descricao_en' => 'Schönbrunn Palace is a baroque palace in Vienna, Austria. It was the summer residence of the Habsburgs and is one of the most important cultural monuments in Austria.',
                'descricao_es' => 'El Palacio de Schönbrunn es un palacio barroco en Viena, Austria. Fue la residencia de verano de los Habsburgo y es uno de los monumentos culturales más importantes de Austria.',
            ],
            [
                'cidade' => 'Salzburgo',
                'pais' => 'Áustria',
                'categoria' => 'Cultural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Salzburgo, Áustria',
                'nome_pt' => 'Fortaleza de Hohensalzburg',
                'nome_en' => 'Hohensalzburg Fortress',
                'nome_es' => 'Fortaleza de Hohensalzburg',
                'descricao_pt' => 'A Fortaleza de Hohensalzburg é um castelo medieval localizado em Salzburgo, Áustria. É uma das maiores fortalezas medievais da Europa.',
                'descricao_en' => 'Hohensalzburg Fortress is a medieval castle located in Salzburg, Austria. It is one of the largest medieval fortresses in Europe.',
                'descricao_es' => 'La Fortaleza de Hohensalzburg es un castillo medieval ubicado en Salzburgo, Austria. Es una de las fortalezas medievales más grandes de Europa.',
            ],
            [
                'cidade' => 'Zurique',
                'pais' => 'Suíça',
                'categoria' => 'Cultural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Bahnhofstrasse, Zurique, Suíça',
                'nome_pt' => 'Bahnhofstrasse',
                'nome_en' => 'Bahnhofstrasse',
                'nome_es' => 'Bahnhofstrasse',
                'descricao_pt' => 'Bahnhofstrasse é uma das ruas comerciais mais famosas e exclusivas do mundo, localizada em Zurique, Suíça. É conhecida por suas lojas de luxo.',
                'descricao_en' => 'Bahnhofstrasse is one of the most famous and exclusive shopping streets in the world, located in Zurich, Switzerland. It is known for its luxury shops.',
                'descricao_es' => 'Bahnhofstrasse es una de las calles comerciales más famosas y exclusivas del mundo, ubicada en Zúrich, Suiza. Es conocida por sus tiendas de lujo.',
            ],
            [
                'cidade' => 'Genebra',
                'pais' => 'Suíça',
                'categoria' => 'Natural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Genebra, Suíça',
                'nome_pt' => 'Lago de Genebra',
                'nome_en' => 'Lake Geneva',
                'nome_es' => 'Lago de Ginebra',
                'descricao_pt' => 'O Lago de Genebra é um lago na fronteira entre a Suíça e a França. É o maior lago da Europa Ocidental e um destino turístico popular.',
                'descricao_en' => 'Lake Geneva is a lake on the border between Switzerland and France. It is the largest lake in Western Europe and a popular tourist destination.',
                'descricao_es' => 'El Lago de Ginebra es un lago en la frontera entre Suiza y Francia. Es el lago más grande de Europa Occidental y un destino turístico popular.',
            ],
            [
                'cidade' => 'Cairo',
                'pais' => 'Egito',
                'categoria' => 'Histórico',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Gizé, Cairo, Egito',
                'nome_pt' => 'Pirâmides de Gizé',
                'nome_en' => 'Pyramids of Giza',
                'nome_es' => 'Pirámides de Giza',
                'descricao_pt' => 'As Pirâmides de Gizé são um complexo de antigas pirâmides egípcias localizadas em Gizé, Cairo. Incluem a Grande Pirâmide, a única das Sete Maravilhas do Mundo Antigo ainda existente.',
                'descricao_en' => 'The Pyramids of Giza are a complex of ancient Egyptian pyramids located in Giza, Cairo. They include the Great Pyramid, the only one of the Seven Wonders of the Ancient World still in existence.',
                'descricao_es' => 'Las Pirámides de Giza son un complejo de antiguas pirámides egipcias ubicadas en Giza, El Cairo. Incluyen la Gran Pirámide, la única de las Siete Maravillas del Mundo Antiguo que aún existe.',
            ],
            [
                'cidade' => 'Luxor',
                'pais' => 'Egito',
                'categoria' => 'Histórico',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Luxor, Egito',
                'nome_pt' => 'Vale dos Reis',
                'nome_en' => 'Valley of the Kings',
                'nome_es' => 'Valle de los Reyes',
                'descricao_pt' => 'O Vale dos Reis é um vale no Egito onde, por um período de quase 500 anos, do século XVI ao XI a.C., foram construídos túmulos para reis e nobres do Novo Reino.',
                'descricao_en' => 'The Valley of the Kings is a valley in Egypt where, for a period of nearly 500 years, from the 16th to 11th century BC, tombs were built for kings and nobles of the New Kingdom.',
                'descricao_es' => 'El Valle de los Reyes es un valle en Egipto donde, por un período de casi 500 años, del siglo XVI al XI a.C., se construyeron tumbas para reyes y nobles del Nuevo Reino.',
            ],
            [
                'cidade' => 'Marrakech',
                'pais' => 'Marrocos',
                'categoria' => 'Cultural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Marrakech, Marrocos',
                'nome_pt' => 'Medina de Marrakech',
                'nome_en' => 'Marrakech Medina',
                'nome_es' => 'Medina de Marrakech',
                'descricao_pt' => 'A Medina de Marrakech é o centro histórico da cidade, cercado por muralhas do século XII. É um Patrimônio Mundial da UNESCO e um dos centros culturais mais importantes do Marrocos.',
                'descricao_en' => 'The Marrakech Medina is the historic center of the city, surrounded by 12th-century walls. It is a UNESCO World Heritage Site and one of the most important cultural centers in Morocco.',
                'descricao_es' => 'La Medina de Marrakech es el centro histórico de la ciudad, rodeado por murallas del siglo XII. Es un Sitio del Patrimonio Mundial de la UNESCO y uno de los centros culturales más importantes de Marruecos.',
            ],
            [
                'cidade' => 'Fez',
                'pais' => 'Marrocos',
                'categoria' => 'Cultural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Fez, Marrocos',
                'nome_pt' => 'Medina de Fez',
                'nome_en' => 'Fez Medina',
                'nome_es' => 'Medina de Fez',
                'descricao_pt' => 'A Medina de Fez é a maior zona urbana livre de carros do mundo. É um Patrimônio Mundial da UNESCO e um dos centros culturais mais importantes do Marrocos.',
                'descricao_en' => 'The Fez Medina is the largest car-free urban area in the world. It is a UNESCO World Heritage Site and one of the most important cultural centers in Morocco.',
                'descricao_es' => 'La Medina de Fez es la zona urbana libre de automóviles más grande del mundo. Es un Sitio del Patrimonio Mundial de la UNESCO y uno de los centros culturales más importantes de Marruecos.',
            ],
            [
                'cidade' => 'Tunísia',
                'pais' => 'Tunísia',
                'categoria' => 'Histórico',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Cartago, Tunísia',
                'nome_pt' => 'Ruínas de Cartago',
                'nome_en' => 'Carthage Ruins',
                'nome_es' => 'Ruinas de Cartago',
                'descricao_pt' => 'As Ruínas de Cartago são os restos da antiga cidade de Cartago, localizada na Tunísia. Cartago foi uma das cidades mais importantes da Antiguidade.',
                'descricao_en' => 'The Carthage Ruins are the remains of the ancient city of Carthage, located in Tunisia. Carthage was one of the most important cities of Antiquity.',
                'descricao_es' => 'Las Ruinas de Cartago son los restos de la antigua ciudad de Cartago, ubicada en Túnez. Cartago fue una de las ciudades más importantes de la Antigüedad.',
            ],
            // 41-50: Destinos Americanos e Caribenhos
            [
                'cidade' => 'São Paulo',
                'pais' => 'Brasil',
                'categoria' => 'Arquitetônico',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Av. Paulista, São Paulo - SP, Brasil',
                'nome_pt' => 'Avenida Paulista',
                'nome_en' => 'Paulista Avenue',
                'nome_es' => 'Avenida Paulista',
                'descricao_pt' => 'A Avenida Paulista é uma das principais vias da cidade de São Paulo, Brasil. É conhecida por sua importância econômica e cultural, abrigando diversos museus e centros culturais.',
                'descricao_en' => 'Paulista Avenue is one of the main thoroughfares in the city of São Paulo, Brazil. It is known for its economic and cultural importance, housing various museums and cultural centers.',
                'descricao_es' => 'La Avenida Paulista es una de las principales vías de la ciudad de São Paulo, Brasil. Es conocida por su importancia económica y cultural, albergando diversos museos y centros culturales.',
            ],
            [
                'cidade' => 'Brasília',
                'pais' => 'Brasil',
                'categoria' => 'Arquitetônico',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Brasília - DF, Brasil',
                'nome_pt' => 'Catedral de Brasília',
                'nome_en' => 'Brasília Cathedral',
                'nome_es' => 'Catedral de Brasilia',
                'descricao_pt' => 'A Catedral de Brasília é uma catedral católica projetada pelo arquiteto Oscar Niemeyer. É um dos marcos arquitetônicos mais importantes de Brasília e do Brasil.',
                'descricao_en' => 'Brasília Cathedral is a Catholic cathedral designed by architect Oscar Niemeyer. It is one of the most important architectural landmarks of Brasília and Brazil.',
                'descricao_es' => 'La Catedral de Brasilia es una catedral católica diseñada por el arquitecto Oscar Niemeyer. Es uno de los hitos arquitectónicos más importantes de Brasilia y Brasil.',
            ],
            [
                'cidade' => 'Salvador',
                'pais' => 'Brasil',
                'categoria' => 'Histórico',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Pelourinho, Salvador - BA, Brasil',
                'nome_pt' => 'Pelourinho',
                'nome_en' => 'Pelourinho',
                'nome_es' => 'Pelourinho',
                'descricao_pt' => 'O Pelourinho é o centro histórico de Salvador, Bahia, Brasil. É conhecido por suas ruas de paralelepípedos e arquitetura colonial portuguesa colorida.',
                'descricao_en' => 'Pelourinho is the historic center of Salvador, Bahia, Brazil. It is known for its cobblestone streets and colorful Portuguese colonial architecture.',
                'descricao_es' => 'El Pelourinho es el centro histórico de Salvador, Bahía, Brasil. Es conocido por sus calles empedradas y arquitectura colonial portuguesa colorida.',
            ],
            [
                'cidade' => 'Buenos Aires',
                'pais' => 'Argentina',
                'categoria' => 'Cultural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'La Boca, Buenos Aires, Argentina',
                'nome_pt' => 'Caminito',
                'nome_en' => 'Caminito',
                'nome_es' => 'Caminito',
                'descricao_pt' => 'Caminito é uma rua museu e um tradicional caminho em La Boca, Buenos Aires, Argentina. É conhecido por suas casas coloridas e importância cultural.',
                'descricao_en' => 'Caminito is a street museum and traditional path in La Boca, Buenos Aires, Argentina. It is known for its colorful houses and cultural importance.',
                'descricao_es' => 'Caminito es una calle museo y un camino tradicional en La Boca, Buenos Aires, Argentina. Es conocido por sus casas coloridas e importancia cultural.',
            ],
            [
                'cidade' => 'Lima',
                'pais' => 'Peru',
                'categoria' => 'Histórico',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Lima, Peru',
                'nome_pt' => 'Centro Histórico de Lima',
                'nome_en' => 'Historic Center of Lima',
                'nome_es' => 'Centro Histórico de Lima',
                'descricao_pt' => 'O Centro Histórico de Lima é o centro histórico da cidade de Lima, Peru. É um Patrimônio Mundial da UNESCO e um dos centros históricos mais importantes da América do Sul.',
                'descricao_en' => 'The Historic Center of Lima is the historic center of the city of Lima, Peru. It is a UNESCO World Heritage Site and one of the most important historic centers in South America.',
                'descricao_es' => 'El Centro Histórico de Lima es el centro histórico de la ciudad de Lima, Perú. Es un Sitio del Patrimonio Mundial de la UNESCO y uno de los centros históricos más importantes de América del Sur.',
            ],
            [
                'cidade' => 'Santiago',
                'pais' => 'Chile',
                'categoria' => 'Natural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Santiago, Chile',
                'nome_pt' => 'Cerro San Cristóbal',
                'nome_en' => 'San Cristóbal Hill',
                'nome_es' => 'Cerro San Cristóbal',
                'descricao_pt' => 'O Cerro San Cristóbal é uma colina em Santiago, Chile. É um dos principais pontos turísticos da cidade, oferecendo vistas panorâmicas espetaculares.',
                'descricao_en' => 'San Cristóbal Hill is a hill in Santiago, Chile. It is one of the main tourist attractions of the city, offering spectacular panoramic views.',
                'descricao_es' => 'El Cerro San Cristóbal es una colina en Santiago, Chile. Es una de las principales atracciones turísticas de la ciudad, ofreciendo vistas panorámicas espectaculares.',
            ],
            [
                'cidade' => 'Bogotá',
                'pais' => 'Colômbia',
                'categoria' => 'Cultural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Bogotá, Colômbia',
                'nome_pt' => 'Museu do Ouro',
                'nome_en' => 'Gold Museum',
                'nome_es' => 'Museo del Oro',
                'descricao_pt' => 'O Museu do Ouro é um museu em Bogotá, Colômbia, que abriga uma das maiores coleções de artefatos de ouro pré-colombianos do mundo.',
                'descricao_en' => 'The Gold Museum is a museum in Bogotá, Colombia, that houses one of the largest collections of pre-Columbian gold artifacts in the world.',
                'descricao_es' => 'El Museo del Oro es un museo en Bogotá, Colombia, que alberga una de las mayores colecciones de artefactos de oro precolombinos del mundo.',
            ],
            [
                'cidade' => 'Havana',
                'pais' => 'Cuba',
                'categoria' => 'Histórico',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Havana, Cuba',
                'nome_pt' => 'Havana Velha',
                'nome_en' => 'Old Havana',
                'nome_es' => 'La Habana Vieja',
                'descricao_pt' => 'Havana Velha é o centro histórico de Havana, Cuba. É um Patrimônio Mundial da UNESCO e um dos centros históricos mais importantes do Caribe.',
                'descricao_en' => 'Old Havana is the historic center of Havana, Cuba. It is a UNESCO World Heritage Site and one of the most important historic centers in the Caribbean.',
                'descricao_es' => 'La Habana Vieja es el centro histórico de La Habana, Cuba. Es un Sitio del Patrimonio Mundial de la UNESCO y uno de los centros históricos más importantes del Caribe.',
            ],
            [
                'cidade' => 'Cidade do México',
                'pais' => 'México',
                'categoria' => 'Histórico',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Cidade do México, México',
                'nome_pt' => 'Teotihuacán',
                'nome_en' => 'Teotihuacán',
                'nome_es' => 'Teotihuacán',
                'descricao_pt' => 'Teotihuacán é uma antiga cidade mesoamericana localizada no Vale do México. É conhecida por suas pirâmides monumentais e sua importância histórica.',
                'descricao_en' => 'Teotihuacán is an ancient Mesoamerican city located in the Valley of Mexico. It is known for its monumental pyramids and historical importance.',
                'descricao_es' => 'Teotihuacán es una antigua ciudad mesoamericana ubicada en el Valle de México. Es conocida por sus pirámides monumentales y su importancia histórica.',
            ],
            // 51-60: Destinos Norte-Americanos e Europeus
            [
                'cidade' => 'Nova York',
                'pais' => 'Estados Unidos',
                'categoria' => 'Arquitetônico',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Manhattan, Nova York, NY, Estados Unidos',
                'nome_pt' => 'Times Square',
                'nome_en' => 'Times Square',
                'nome_es' => 'Times Square',
                'descricao_pt' => 'Times Square é uma importante interseção comercial em Manhattan, Nova York. É conhecida por suas luzes neon brilhantes e como centro do entretenimento mundial.',
                'descricao_en' => 'Times Square is a major commercial intersection in Manhattan, New York. It is known for its bright neon lights and as the center of world entertainment.',
                'descricao_es' => 'Times Square es una importante intersección comercial en Manhattan, Nueva York. Es conocida por sus brillantes luces de neón y como centro del entretenimiento mundial.',
            ],
            [
                'cidade' => 'Los Angeles',
                'pais' => 'Estados Unidos',
                'categoria' => 'Cultural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Hollywood, Los Angeles, CA, Estados Unidos',
                'nome_pt' => 'Hollywood Walk of Fame',
                'nome_en' => 'Hollywood Walk of Fame',
                'nome_es' => 'Paseo de la Fama de Hollywood',
                'descricao_pt' => 'O Hollywood Walk of Fame é uma calçada ao longo de Hollywood Boulevard e Vine Street em Hollywood, Los Angeles. É famosa por suas estrelas de bronze homenageando celebridades.',
                'descricao_en' => 'The Hollywood Walk of Fame is a sidewalk along Hollywood Boulevard and Vine Street in Hollywood, Los Angeles. It is famous for its bronze stars honoring celebrities.',
                'descricao_es' => 'El Paseo de la Fama de Hollywood es una acera a lo largo de Hollywood Boulevard y Vine Street en Hollywood, Los Angeles. Es famoso por sus estrellas de bronce que honran a celebridades.',
            ],
            [
                'cidade' => 'São Francisco',
                'pais' => 'Estados Unidos',
                'categoria' => 'Arquitetônico',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'São Francisco, CA, Estados Unidos',
                'nome_pt' => 'Golden Gate Bridge',
                'nome_en' => 'Golden Gate Bridge',
                'nome_es' => 'Puente Golden Gate',
                'descricao_pt' => 'A Golden Gate Bridge é uma ponte suspensa que atravessa o Golden Gate, o estreito entre São Francisco e o Condado de Marin, Califórnia.',
                'descricao_en' => 'The Golden Gate Bridge is a suspension bridge spanning the Golden Gate, the strait between San Francisco and Marin County, California.',
                'descricao_es' => 'El Puente Golden Gate es un puente colgante que cruza el Golden Gate, el estrecho entre San Francisco y el Condado de Marin, California.',
            ],
            [
                'cidade' => 'Las Vegas',
                'pais' => 'Estados Unidos',
                'categoria' => 'Cultural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Las Vegas Strip, Las Vegas, NV, Estados Unidos',
                'nome_pt' => 'Las Vegas Strip',
                'nome_en' => 'Las Vegas Strip',
                'nome_es' => 'Las Vegas Strip',
                'descricao_pt' => 'A Las Vegas Strip é uma seção de 6,8 km da Las Vegas Boulevard South em Paradise e Winchester, Nevada. É conhecida por sua concentração de cassinos e hotéis.',
                'descricao_en' => 'The Las Vegas Strip is a 6.8 km section of Las Vegas Boulevard South in Paradise and Winchester, Nevada. It is known for its concentration of casinos and hotels.',
                'descricao_es' => 'La Las Vegas Strip es una sección de 6,8 km de Las Vegas Boulevard South en Paradise y Winchester, Nevada. Es conocida por su concentración de casinos y hoteles.',
            ],
            [
                'cidade' => 'Miami',
                'pais' => 'Estados Unidos',
                'categoria' => 'Cultural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Miami Beach, FL, Estados Unidos',
                'nome_pt' => 'South Beach',
                'nome_en' => 'South Beach',
                'nome_es' => 'South Beach',
                'descricao_pt' => 'South Beach é um bairro de Miami Beach, Flórida, conhecido por suas praias, vida noturna e arquitetura Art Deco.',
                'descricao_en' => 'South Beach is a neighborhood in Miami Beach, Florida, known for its beaches, nightlife, and Art Deco architecture.',
                'descricao_es' => 'South Beach es un vecindario en Miami Beach, Florida, conocido por sus playas, vida nocturna y arquitectura Art Deco.',
            ],
            [
                'cidade' => 'Toronto',
                'pais' => 'Canadá',
                'categoria' => 'Arquitetônico',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Toronto, ON, Canadá',
                'nome_pt' => 'CN Tower',
                'nome_en' => 'CN Tower',
                'nome_es' => 'CN Tower',
                'descricao_pt' => 'A CN Tower é uma torre de telecomunicações e observação em Toronto, Ontário, Canadá. Com 553,3 metros de altura, foi a estrutura mais alta do mundo de 1976 a 2007.',
                'descricao_en' => 'The CN Tower is a telecommunications and observation tower in Toronto, Ontario, Canada. At 553.3 meters tall, it was the tallest structure in the world from 1976 to 2007.',
                'descricao_es' => 'La CN Tower es una torre de telecomunicaciones y observación en Toronto, Ontario, Canadá. Con 553,3 metros de altura, fue la estructura más alta del mundo de 1976 a 2007.',
            ],
            [
                'cidade' => 'Vancouver',
                'pais' => 'Canadá',
                'categoria' => 'Natural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Vancouver, BC, Canadá',
                'nome_pt' => 'Stanley Park',
                'nome_en' => 'Stanley Park',
                'nome_es' => 'Stanley Park',
                'descricao_pt' => 'Stanley Park é um parque urbano de 405 hectares em Vancouver, Colúmbia Britânica, Canadá. É um dos maiores parques urbanos da América do Norte.',
                'descricao_en' => 'Stanley Park is a 405-hectare urban park in Vancouver, British Columbia, Canada. It is one of the largest urban parks in North America.',
                'descricao_es' => 'Stanley Park es un parque urbano de 405 hectáreas en Vancouver, Columbia Británica, Canadá. Es uno de los parques urbanos más grandes de América del Norte.',
            ],
            [
                'cidade' => 'Montreal',
                'pais' => 'Canadá',
                'categoria' => 'Cultural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Montreal, QC, Canadá',
                'nome_pt' => 'Basilique Notre-Dame',
                'nome_en' => 'Notre-Dame Basilica',
                'nome_es' => 'Basílica Notre-Dame',
                'descricao_pt' => 'A Basílica Notre-Dame é uma basílica católica em Montreal, Quebec, Canadá. É um dos exemplos mais notáveis da arquitetura neogótica na América do Norte.',
                'descricao_en' => 'Notre-Dame Basilica is a Catholic basilica in Montreal, Quebec, Canada. It is one of the most notable examples of neo-Gothic architecture in North America.',
                'descricao_es' => 'La Basílica Notre-Dame es una basílica católica en Montreal, Quebec, Canadá. Es uno de los ejemplos más notables de arquitectura neogótica en América del Norte.',
            ],
            [
                'cidade' => 'Quebec',
                'pais' => 'Canadá',
                'categoria' => 'Histórico',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Quebec, QC, Canadá',
                'nome_pt' => 'Vieux-Québec',
                'nome_en' => 'Old Quebec',
                'nome_es' => 'Vieux-Québec',
                'descricao_pt' => 'Vieux-Québec é o centro histórico da cidade de Quebec, Canadá. É um Patrimônio Mundial da UNESCO e um dos centros históricos mais importantes da América do Norte.',
                'descricao_en' => 'Old Quebec is the historic center of Quebec City, Canada. It is a UNESCO World Heritage Site and one of the most important historic centers in North America.',
                'descricao_es' => 'Vieux-Québec es el centro histórico de la Ciudad de Quebec, Canadá. Es un Sitio del Patrimonio Mundial de la UNESCO y uno de los centros históricos más importantes de América del Norte.',
            ],
            // 61-70: Destinos Europeus e Mediterrâneos
            [
                'cidade' => 'Atenas',
                'pais' => 'Grécia',
                'categoria' => 'Histórico',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Atenas, Grécia',
                'nome_pt' => 'Acrópole de Atenas',
                'nome_en' => 'Acropolis of Athens',
                'nome_es' => 'Acrópolis de Atenas',
                'descricao_pt' => 'A Acrópole de Atenas é uma antiga cidadela localizada em uma colina rochosa acima da cidade de Atenas. É um dos sítios arqueológicos mais importantes da Grécia.',
                'descricao_en' => 'The Acropolis of Athens is an ancient citadel located on a rocky hill above the city of Athens. It is one of the most important archaeological sites in Greece.',
                'descricao_es' => 'La Acrópolis de Atenas es una antigua ciudadela ubicada en una colina rocosa sobre la ciudad de Atenas. Es uno de los sitios arqueológicos más importantes de Grecia.',
            ],
            [
                'cidade' => 'Santorini',
                'pais' => 'Grécia',
                'categoria' => 'Natural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Santorini, Grécia',
                'nome_pt' => 'Caldeira de Santorini',
                'nome_en' => 'Santorini Caldera',
                'nome_es' => 'Caldera de Santorini',
                'descricao_pt' => 'A Caldeira de Santorini é uma caldeira vulcânica submersa localizada na ilha de Santorini, Grécia. É conhecida por suas vistas espetaculares e arquitetura única.',
                'descricao_en' => 'The Santorini Caldera is a submerged volcanic caldera located on the island of Santorini, Greece. It is known for its spectacular views and unique architecture.',
                'descricao_es' => 'La Caldera de Santorini es una caldera volcánica sumergida ubicada en la isla de Santorini, Grecia. Es conocida por sus vistas espectaculares y arquitectura única.',
            ],
            [
                'cidade' => 'Mikonos',
                'pais' => 'Grécia',
                'categoria' => 'Cultural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Mikonos, Grécia',
                'nome_pt' => 'Moinhos de Vento de Mikonos',
                'nome_en' => 'Windmills of Mykonos',
                'nome_es' => 'Molinos de Viento de Mikonos',
                'descricao_pt' => 'Os Moinhos de Vento de Mikonos são um conjunto de moinhos de vento localizados na ilha de Mikonos, Grécia. São um dos símbolos mais reconhecíveis da ilha.',
                'descricao_en' => 'The Windmills of Mykonos are a set of windmills located on the island of Mykonos, Greece. They are one of the most recognizable symbols of the island.',
                'descricao_es' => 'Los Molinos de Viento de Mikonos son un conjunto de molinos de viento ubicados en la isla de Mikonos, Grecia. Son uno de los símbolos más reconocibles de la isla.',
            ],
            [
                'cidade' => 'Rodes',
                'pais' => 'Grécia',
                'categoria' => 'Histórico',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Rodes, Grécia',
                'nome_pt' => 'Cidade Medieval de Rodes',
                'nome_en' => 'Medieval City of Rhodes',
                'nome_es' => 'Ciudad Medieval de Rodas',
                'descricao_pt' => 'A Cidade Medieval de Rodes é o centro histórico da cidade de Rodes, Grécia. É um Patrimônio Mundial da UNESCO e um dos centros medievais mais bem preservados da Europa.',
                'descricao_en' => 'The Medieval City of Rhodes is the historic center of the city of Rhodes, Greece. It is a UNESCO World Heritage Site and one of the best-preserved medieval centers in Europe.',
                'descricao_es' => 'La Ciudad Medieval de Rodas es el centro histórico de la ciudad de Rodas, Grecia. Es un Sitio del Patrimonio Mundial de la UNESCO y uno de los centros medievales mejor conservados de Europa.',
            ],
            [
                'cidade' => 'Creta',
                'pais' => 'Grécia',
                'categoria' => 'Histórico',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Creta, Grécia',
                'nome_pt' => 'Palácio de Cnossos',
                'nome_en' => 'Palace of Knossos',
                'nome_es' => 'Palacio de Cnosos',
                'descricao_pt' => 'O Palácio de Cnossos é um sítio arqueológico localizado na ilha de Creta, Grécia. É o maior sítio arqueológico da Idade do Bronze em Creta.',
                'descricao_en' => 'The Palace of Knossos is an archaeological site located on the island of Crete, Greece. It is the largest Bronze Age archaeological site on Crete.',
                'descricao_es' => 'El Palacio de Cnosos es un sitio arqueológico ubicado en la isla de Creta, Grecia. Es el sitio arqueológico más grande de la Edad del Bronce en Creta.',
            ],
            [
                'cidade' => 'Malta',
                'pais' => 'Malta',
                'categoria' => 'Histórico',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Valletta, Malta',
                'nome_pt' => 'Valletta',
                'nome_en' => 'Valletta',
                'nome_es' => 'Valletta',
                'descricao_pt' => 'Valletta é a capital de Malta e um Patrimônio Mundial da UNESCO. É conhecida por sua arquitetura barroca e importância histórica.',
                'descricao_en' => 'Valletta is the capital of Malta and a UNESCO World Heritage Site. It is known for its Baroque architecture and historical importance.',
                'descricao_es' => 'Valletta es la capital de Malta y un Sitio del Patrimonio Mundial de la UNESCO. Es conocida por su arquitectura barroca e importancia histórica.',
            ],
            [
                'cidade' => 'Chipre',
                'pais' => 'Chipre',
                'categoria' => 'Histórico',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Pafos, Chipre',
                'nome_pt' => 'Pafos',
                'nome_en' => 'Paphos',
                'nome_es' => 'Pafos',
                'descricao_pt' => 'Pafos é uma cidade costeira em Chipre conhecida por suas ruínas antigas e importância histórica. É um Patrimônio Mundial da UNESCO.',
                'descricao_en' => 'Paphos is a coastal city in Cyprus known for its ancient ruins and historical importance. It is a UNESCO World Heritage Site.',
                'descricao_es' => 'Pafos es una ciudad costera en Chipre conocida por sus ruinas antiguas e importancia histórica. Es un Sitio del Patrimonio Mundial de la UNESCO.',
            ],
            [
                'cidade' => 'Sicília',
                'pais' => 'Itália',
                'categoria' => 'Natural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Sicília, Itália',
                'nome_pt' => 'Monte Etna',
                'nome_en' => 'Mount Etna',
                'nome_es' => 'Monte Etna',
                'descricao_pt' => 'O Monte Etna é um vulcão ativo na costa leste da Sicília, Itália. É o vulcão mais alto da Europa continental e um dos mais ativos do mundo.',
                'descricao_en' => 'Mount Etna is an active volcano on the east coast of Sicily, Italy. It is the tallest active volcano in continental Europe and one of the most active in the world.',
                'descricao_es' => 'El Monte Etna es un volcán activo en la costa este de Sicilia, Italia. Es el volcán activo más alto de la Europa continental y uno de los más activos del mundo.',
            ],
            [
                'cidade' => 'Sardenha',
                'pais' => 'Itália',
                'categoria' => 'Natural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Sardenha, Itália',
                'nome_pt' => 'Costa Esmeralda',
                'nome_en' => 'Emerald Coast',
                'nome_es' => 'Costa Esmeralda',
                'descricao_pt' => 'A Costa Esmeralda é uma região costeira na Sardenha, Itália, conhecida por suas praias de areia branca e águas cristalinas.',
                'descricao_en' => 'The Emerald Coast is a coastal region in Sardinia, Italy, known for its white sand beaches and crystal clear waters.',
                'descricao_es' => 'La Costa Esmeralda es una región costera en Cerdeña, Italia, conocida por sus playas de arena blanca y aguas cristalinas.',
            ],
            // 71-80: Destinos Nórdicos e Bálticos
            [
                'cidade' => 'Estocolmo',
                'pais' => 'Suécia',
                'categoria' => 'Cultural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Estocolmo, Suécia',
                'nome_pt' => 'Gamla Stan',
                'nome_en' => 'Gamla Stan',
                'nome_es' => 'Gamla Stan',
                'descricao_pt' => 'Gamla Stan é o centro histórico de Estocolmo, Suécia. É conhecido por suas ruas medievais, arquitetura histórica e palácios reais.',
                'descricao_en' => 'Gamla Stan is the historic center of Stockholm, Sweden. It is known for its medieval streets, historic architecture, and royal palaces.',
                'descricao_es' => 'Gamla Stan es el centro histórico de Estocolmo, Suecia. Es conocido por sus calles medievales, arquitectura histórica y palacios reales.',
            ],
            [
                'cidade' => 'Copenhague',
                'pais' => 'Dinamarca',
                'categoria' => 'Cultural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Copenhague, Dinamarca',
                'nome_pt' => 'Nyhavn',
                'nome_en' => 'Nyhavn',
                'nome_es' => 'Nyhavn',
                'descricao_pt' => 'Nyhavn é um canal e distrito de entretenimento em Copenhague, Dinamarca. É conhecido por suas casas coloridas e barcos históricos.',
                'descricao_en' => 'Nyhavn is a canal and entertainment district in Copenhagen, Denmark. It is known for its colorful houses and historic boats.',
                'descricao_es' => 'Nyhavn es un canal y distrito de entretenimiento en Copenhague, Dinamarca. Es conocido por sus casas coloridas y barcos históricos.',
            ],
            [
                'cidade' => 'Oslo',
                'pais' => 'Noruega',
                'categoria' => 'Cultural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Oslo, Noruega',
                'nome_pt' => 'Vigeland Park',
                'nome_en' => 'Vigeland Park',
                'nome_es' => 'Parque Vigeland',
                'descricao_pt' => 'O Parque Vigeland é um parque de esculturas em Oslo, Noruega. É o maior parque de esculturas do mundo criado por um único artista.',
                'descricao_en' => 'Vigeland Park is a sculpture park in Oslo, Norway. It is the largest sculpture park in the world created by a single artist.',
                'descricao_es' => 'El Parque Vigeland es un parque de esculturas en Oslo, Noruega. Es el parque de esculturas más grande del mundo creado por un solo artista.',
            ],
            [
                'cidade' => 'Helsinque',
                'pais' => 'Finlândia',
                'categoria' => 'Arquitetônico',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Helsinque, Finlândia',
                'nome_pt' => 'Catedral de Helsinque',
                'nome_en' => 'Helsinki Cathedral',
                'nome_es' => 'Catedral de Helsinki',
                'descricao_pt' => 'A Catedral de Helsinque é uma catedral luterana em Helsinque, Finlândia. É um dos marcos mais reconhecíveis da cidade.',
                'descricao_en' => 'Helsinki Cathedral is a Lutheran cathedral in Helsinki, Finland. It is one of the most recognizable landmarks of the city.',
                'descricao_es' => 'La Catedral de Helsinki es una catedral luterana en Helsinki, Finlandia. Es uno de los hitos más reconocibles de la ciudad.',
            ],
            [
                'cidade' => 'Reykjavik',
                'pais' => 'Islândia',
                'categoria' => 'Natural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Reykjavik, Islândia',
                'nome_pt' => 'Lagoa Azul',
                'nome_en' => 'Blue Lagoon',
                'nome_es' => 'Laguna Azul',
                'descricao_pt' => 'A Lagoa Azul é um spa geotérmico localizado em um campo de lava na Islândia. É uma das atrações turísticas mais populares do país.',
                'descricao_en' => 'The Blue Lagoon is a geothermal spa located in a lava field in Iceland. It is one of the most popular tourist attractions in the country.',
                'descricao_es' => 'La Laguna Azul es un spa geotérmico ubicado en un campo de lava en Islandia. Es una de las atracciones turísticas más populares del país.',
            ],
            [
                'cidade' => 'Tallinn',
                'pais' => 'Estônia',
                'categoria' => 'Histórico',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Tallinn, Estônia',
                'nome_pt' => 'Cidade Velha de Tallinn',
                'nome_en' => 'Old Town of Tallinn',
                'nome_es' => 'Ciudad Vieja de Tallin',
                'descricao_pt' => 'A Cidade Velha de Tallinn é o centro histórico da capital da Estônia. É um Patrimônio Mundial da UNESCO e um dos centros medievais mais bem preservados da Europa.',
                'descricao_en' => 'The Old Town of Tallinn is the historic center of the Estonian capital. It is a UNESCO World Heritage Site and one of the best-preserved medieval centers in Europe.',
                'descricao_es' => 'La Ciudad Vieja de Tallin es el centro histórico de la capital de Estonia. Es un Sitio del Patrimonio Mundial de la UNESCO y uno de los centros medievales mejor conservados de Europa.',
            ],
            [
                'cidade' => 'Riga',
                'pais' => 'Letônia',
                'categoria' => 'Histórico',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Riga, Letônia',
                'nome_pt' => 'Centro Histórico de Riga',
                'nome_en' => 'Historic Center of Riga',
                'nome_es' => 'Centro Histórico de Riga',
                'descricao_pt' => 'O Centro Histórico de Riga é o centro histórico da capital da Letônia. É um Patrimônio Mundial da UNESCO e um dos centros históricos mais importantes dos países bálticos.',
                'descricao_en' => 'The Historic Center of Riga is the historic center of the Latvian capital. It is a UNESCO World Heritage Site and one of the most important historic centers in the Baltic countries.',
                'descricao_es' => 'El Centro Histórico de Riga es el centro histórico de la capital de Letonia. Es un Sitio del Patrimonio Mundial de la UNESCO y uno de los centros históricos más importantes de los países bálticos.',
            ],
            [
                'cidade' => 'Vilnius',
                'pais' => 'Lituânia',
                'categoria' => 'Histórico',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Vilnius, Lituânia',
                'nome_pt' => 'Centro Histórico de Vilnius',
                'nome_en' => 'Historic Center of Vilnius',
                'nome_es' => 'Centro Histórico de Vilnius',
                'descricao_pt' => 'O Centro Histórico de Vilnius é o centro histórico da capital da Lituânia. É um Patrimônio Mundial da UNESCO e um dos centros históricos mais importantes dos países bálticos.',
                'descricao_en' => 'The Historic Center of Vilnius is the historic center of the Lithuanian capital. It is a UNESCO World Heritage Site and one of the most important historic centers in the Baltic countries.',
                'descricao_es' => 'El Centro Histórico de Vilnius es el centro histórico de la capital de Lituania. Es un Sitio del Patrimonio Mundial de la UNESCO y uno de los centros históricos más importantes de los países bálticos.',
            ],
            [
                'cidade' => 'São Petersburgo',
                'pais' => 'Rússia',
                'categoria' => 'Cultural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'São Petersburgo, Rússia',
                'nome_pt' => 'Museu Hermitage',
                'nome_en' => 'Hermitage Museum',
                'nome_es' => 'Museo del Hermitage',
                'descricao_pt' => 'O Museu Hermitage é um dos maiores e mais antigos museus de arte do mundo, localizado em São Petersburgo, Rússia.',
                'descricao_en' => 'The Hermitage Museum is one of the largest and oldest art museums in the world, located in St. Petersburg, Russia.',
                'descricao_es' => 'El Museo del Hermitage es uno de los museos de arte más grandes y antiguos del mundo, ubicado en San Petersburgo, Rusia.',
            ],
            // 81-90: Destinos Asiáticos e Africanos
            [
                'cidade' => 'Osaka',
                'pais' => 'Japão',
                'categoria' => 'Cultural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Osaka, Japão',
                'nome_pt' => 'Castelo de Osaka',
                'nome_en' => 'Osaka Castle',
                'nome_es' => 'Castillo de Osaka',
                'descricao_pt' => 'O Castelo de Osaka é um castelo japonês localizado em Osaka, Japão. É um dos castelos mais famosos do Japão e um símbolo da cidade.',
                'descricao_en' => 'Osaka Castle is a Japanese castle located in Osaka, Japan. It is one of the most famous castles in Japan and a symbol of the city.',
                'descricao_es' => 'El Castillo de Osaka es un castillo japonés ubicado en Osaka, Japón. Es uno de los castillos más famosos de Japón y un símbolo de la ciudad.',
            ],
            [
                'cidade' => 'Quioto',
                'pais' => 'Japão',
                'categoria' => 'Cultural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Quioto, Japão',
                'nome_pt' => 'Templo Kinkaku-ji',
                'nome_en' => 'Kinkaku-ji Temple',
                'nome_es' => 'Templo Kinkaku-ji',
                'descricao_pt' => 'O Templo Kinkaku-ji, também conhecido como Pavilhão Dourado, é um templo zen em Quioto, Japão. É um Patrimônio Mundial da UNESCO.',
                'descricao_en' => 'Kinkaku-ji Temple, also known as the Golden Pavilion, is a Zen temple in Kyoto, Japan. It is a UNESCO World Heritage Site.',
                'descricao_es' => 'El Templo Kinkaku-ji, también conocido como el Pabellón Dorado, es un templo zen en Kioto, Japón. Es un Sitio del Patrimonio Mundial de la UNESCO.',
            ],
            [
                'cidade' => 'Nara',
                'pais' => 'Japão',
                'categoria' => 'Cultural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Nara, Japão',
                'nome_pt' => 'Templo Todai-ji',
                'nome_en' => 'Todai-ji Temple',
                'nome_es' => 'Templo Todai-ji',
                'descricao_pt' => 'O Templo Todai-ji é um templo budista em Nara, Japão. É conhecido por sua estátua gigante de Buda e é um Patrimônio Mundial da UNESCO.',
                'descricao_en' => 'Todai-ji Temple is a Buddhist temple in Nara, Japan. It is known for its giant Buddha statue and is a UNESCO World Heritage Site.',
                'descricao_es' => 'El Templo Todai-ji es un templo budista en Nara, Japón. Es conocido por su estatua gigante de Buda y es un Sitio del Patrimonio Mundial de la UNESCO.',
            ],
            [
                'cidade' => 'Busan',
                'pais' => 'Coreia do Sul',
                'categoria' => 'Histórico',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Busan, Coreia do Sul',
                'nome_pt' => 'Palácio Gyeongbokgung',
                'nome_en' => 'Gyeongbokgung Palace',
                'nome_es' => 'Palacio Gyeongbokgung',
                'descricao_pt' => 'O Palácio Gyeongbokgung é o maior dos cinco grandes palácios construídos durante a dinastia Joseon em Busan, Coreia do Sul.',
                'descricao_en' => 'Gyeongbokgung Palace is the largest of the five great palaces built during the Joseon Dynasty in Busan, South Korea.',
                'descricao_es' => 'El Palacio Gyeongbokgung es el más grande de los cinco grandes palacios construidos durante la dinastía Joseon en Busan, Coreia del Sur.',
            ],
            [
                'cidade' => 'Daegu',
                'pais' => 'Coreia do Sul',
                'categoria' => 'Cultural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Daegu, Coreia do Sul',
                'nome_pt' => 'Templo Beomeosa',
                'nome_en' => 'Beomeosa Temple',
                'nome_es' => 'Templo Beomeosa',
                'descricao_pt' => 'O Templo Beomeosa é um templo budista em Daegu, Coreia do Sul. É um dos templos mais importantes da Coreia e um dos mais antigos.',
                'descricao_en' => 'Beomeosa Temple is a Buddhist temple in Daegu, South Korea. It is one of the most important temples in Korea and one of the oldest.',
                'descricao_es' => 'El Templo Beomeosa es un templo budista en Daegu, Corea del Sur. Es uno de los templos más importantes de Corea y uno de los más antiguos.',
            ],
            [
                'cidade' => 'Ayutthaya',
                'pais' => 'Tailândia',
                'categoria' => 'Religioso',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Ayutthaya, Tailândia',
                'nome_pt' => 'Wat Phra Kaew',
                'nome_en' => 'Wat Phra Kaew',
                'nome_es' => 'Wat Phra Kaew',
                'descricao_pt' => 'Wat Phra Kaew é o templo mais sagrado da Tailândia, localizado em Ayutthaya. É conhecido por abrigar o Buda de Esmeralda.',
                'descricao_en' => 'Wat Phra Kaew is the most sacred temple in Thailand, located in Ayutthaya. It is known for housing the Emerald Buddha.',
                'descricao_es' => 'Wat Phra Kaew es el templo más sagrado de Tailandia, ubicado en Ayutthaya. Es conocido por albergar el Buda de Esmeralda.',
            ],
            [
                'cidade' => 'Chiang Mai',
                'pais' => 'Tailândia',
                'categoria' => 'Cultural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Chiang Mai, Tailândia',
                'nome_pt' => 'Wat Phra That Doi Suthep',
                'nome_en' => 'Wat Phra That Doi Suthep',
                'nome_es' => 'Wat Phra That Doi Suthep',
                'descricao_pt' => 'Wat Phra That Doi Suthep é um templo budista em Chiang Mai, Tailândia. É um dos templos mais importantes e visitados do norte da Tailândia.',
                'descricao_en' => 'Wat Phra That Doi Suthep is a Buddhist temple in Chiang Mai, Thailand. It is one of the most important and visited temples in northern Thailand.',
                'descricao_es' => 'Wat Phra That Doi Suthep es un templo budista en Chiang Mai, Tailandia. Es uno de los templos más importantes y visitados del norte de Tailandia.',
            ],
            [
                'cidade' => 'Phuket',
                'pais' => 'Tailândia',
                'categoria' => 'Natural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Phuket, Tailândia',
                'nome_pt' => 'Baía de Phang Nga',
                'nome_en' => 'Phang Nga Bay',
                'nome_es' => 'Bahía de Phang Nga',
                'descricao_pt' => 'A Baía de Phang Nga é uma baía em Phuket, Tailândia, conhecida por suas formações rochosas de calcário e ilhas espetaculares.',
                'descricao_en' => 'Phang Nga Bay is a bay in Phuket, Thailand, known for its limestone rock formations and spectacular islands.',
                'descricao_es' => 'La Bahía de Phang Nga es una bahía en Phuket, Tailandia, conocida por sus formaciones rocosas de piedra caliza e islas espectaculares.',
            ],
            [
                'cidade' => 'Krabi',
                'pais' => 'Tailândia',
                'categoria' => 'Natural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Krabi, Tailândia',
                'nome_pt' => 'Praia de Railay',
                'nome_en' => 'Railay Beach',
                'nome_es' => 'Playa de Railay',
                'descricao_pt' => 'A Praia de Railay é uma praia em Krabi, Tailândia, conhecida por suas falésias de calcário e acesso apenas por barco.',
                'descricao_en' => 'Railay Beach is a beach in Krabi, Thailand, known for its limestone cliffs and access only by boat.',
                'descricao_es' => 'La Playa de Railay es una playa en Krabi, Tailandia, conocida por sus acantilados de piedra caliza y acceso solo en barco.',
            ],
            // 91-100: Destinos Finais e Especiais
            [
                'cidade' => 'Hanoi',
                'pais' => 'Vietnã',
                'categoria' => 'Cultural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Hanoi, Vietnã',
                'nome_pt' => 'Templo da Literatura',
                'nome_en' => 'Temple of Literature',
                'nome_es' => 'Templo de la Literatura',
                'descricao_pt' => 'O Templo da Literatura é um templo confucionista em Hanoi, Vietnã. Foi a primeira universidade nacional do Vietnã e é um símbolo da educação.',
                'descricao_en' => 'The Temple of Literature is a Confucian temple in Hanoi, Vietnam. It was the first national university of Vietnam and is a symbol of education.',
                'descricao_es' => 'El Templo de la Literatura es un templo confuciano en Hanoi, Vietnam. Fue la primera universidad nacional de Vietnam y es un símbolo de la educación.',
            ],
            [
                'cidade' => 'Ho Chi Minh',
                'pais' => 'Vietnã',
                'categoria' => 'Cultural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Ho Chi Minh, Vietnã',
                'nome_pt' => 'Túneis de Cu Chi',
                'nome_en' => 'Cu Chi Tunnels',
                'nome_es' => 'Túneles de Cu Chi',
                'descricao_pt' => 'Os Túneis de Cu Chi são uma extensa rede de túneis subterrâneos em Ho Chi Minh, Vietnã. Foram usados durante a Guerra do Vietnã.',
                'descricao_en' => 'The Cu Chi Tunnels are an extensive network of underground tunnels in Ho Chi Minh, Vietnam. They were used during the Vietnam War.',
                'descricao_es' => 'Los Túneles de Cu Chi son una extensa red de túneles subterráneos en Ho Chi Minh, Vietnam. Fueron utilizados durante la Guerra de Vietnam.',
            ],
            [
                'cidade' => 'Luang Prabang',
                'pais' => 'Laos',
                'categoria' => 'Cultural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Luang Prabang, Laos',
                'nome_pt' => 'Centro Histórico de Luang Prabang',
                'nome_en' => 'Historic Center of Luang Prabang',
                'nome_es' => 'Centro Histórico de Luang Prabang',
                'descricao_pt' => 'O Centro Histórico de Luang Prabang é o centro histórico da cidade de Luang Prabang, Laos. É um Patrimônio Mundial da UNESCO.',
                'descricao_en' => 'The Historic Center of Luang Prabang is the historic center of the city of Luang Prabang, Laos. It is a UNESCO World Heritage Site.',
                'descricao_es' => 'El Centro Histórico de Luang Prabang es el centro histórico de la ciudad de Luang Prabang, Laos. Es un Sitio del Patrimonio Mundial de la UNESCO.',
            ],
            [
                'cidade' => 'Yangon',
                'pais' => 'Mianmar',
                'categoria' => 'Religioso',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Yangon, Mianmar',
                'nome_pt' => 'Pagode Shwedagon',
                'nome_en' => 'Shwedagon Pagoda',
                'nome_es' => 'Pagoda Shwedagon',
                'descricao_pt' => 'A Pagode Shwedagon é a pagode mais sagrada de Mianmar, localizada em Yangon. É coberta com ouro e é um dos marcos mais importantes do país.',
                'descricao_en' => 'The Shwedagon Pagoda is the most sacred pagoda in Myanmar, located in Yangon. It is covered with gold and is one of the most important landmarks in the country.',
                'descricao_es' => 'La Pagoda Shwedagon es la pagoda más sagrada de Myanmar, ubicada en Yangon. Está cubierta de oro y es uno de los hitos más importantes del país.',
            ],
            [
                'cidade' => 'Bagan',
                'pais' => 'Mianmar',
                'categoria' => 'Histórico',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Bagan, Mianmar',
                'nome_pt' => 'Planície de Bagan',
                'nome_en' => 'Bagan Plains',
                'nome_es' => 'Llanura de Bagan',
                'descricao_pt' => 'A Planície de Bagan é uma área em Mianmar conhecida por suas milhares de templos e pagodes budistas. É um Patrimônio Mundial da UNESCO.',
                'descricao_en' => 'The Bagan Plains is an area in Myanmar known for its thousands of Buddhist temples and pagodas. It is a UNESCO World Heritage Site.',
                'descricao_es' => 'La Llanura de Bagan es un área en Myanmar conocida por sus miles de templos y pagodas budistas. Es un Sitio del Patrimonio Mundial de la UNESCO.',
            ],
            [
                'cidade' => 'Kathmandu',
                'pais' => 'Nepal',
                'categoria' => 'Cultural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Kathmandu, Nepal',
                'nome_pt' => 'Durbar Square',
                'nome_en' => 'Durbar Square',
                'nome_es' => 'Plaza Durbar',
                'descricao_pt' => 'Durbar Square é uma praça em Kathmandu, Nepal, cercada por palácios e templos antigos. É um Patrimônio Mundial da UNESCO.',
                'descricao_en' => 'Durbar Square is a square in Kathmandu, Nepal, surrounded by ancient palaces and temples. It is a UNESCO World Heritage Site.',
                'descricao_es' => 'Durbar Square es una plaza en Katmandú, Nepal, rodeada de antiguos palacios y templos. Es un Sitio del Patrimonio Mundial de la UNESCO.',
            ],
            [
                'cidade' => 'Lhasa',
                'pais' => 'China',
                'categoria' => 'Religioso',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Lhasa, China',
                'nome_pt' => 'Palácio Potala',
                'nome_en' => 'Potala Palace',
                'nome_es' => 'Palacio Potala',
                'descricao_pt' => 'O Palácio Potala é um palácio em Lhasa, China, que foi a residência do Dalai Lama. É um Patrimônio Mundial da UNESCO.',
                'descricao_en' => 'The Potala Palace is a palace in Lhasa, China, that was the residence of the Dalai Lama. It is a UNESCO World Heritage Site.',
                'descricao_es' => 'El Palacio Potala es un palacio en Lhasa, China, que fue la residencia del Dalai Lama. Es un Sitio del Patrimonio Mundial de la UNESCO.',
            ],
            [
                'cidade' => 'Xangai',
                'pais' => 'China',
                'categoria' => 'Arquitetônico',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Xangai, China',
                'nome_pt' => 'Bund',
                'nome_en' => 'The Bund',
                'nome_es' => 'El Bund',
                'descricao_pt' => 'O Bund é uma área em Xangai, China, conhecida por sua arquitetura colonial e vista para o rio Huangpu. É um dos marcos mais reconhecíveis da cidade.',
                'descricao_en' => 'The Bund is an area in Shanghai, China, known for its colonial architecture and view of the Huangpu River. It is one of the most recognizable landmarks of the city.',
                'descricao_es' => 'El Bund es un área en Shanghái, China, conocida por su arquitectura colonial y vista del río Huangpu. Es uno de los hitos más reconocibles de la ciudad.',
            ],
            [
                'cidade' => 'Shenzhen',
                'pais' => 'China',
                'categoria' => 'Cultural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Shenzhen, China',
                'nome_pt' => 'Templo Wong Tai Sin',
                'nome_en' => 'Wong Tai Sin Temple',
                'nome_es' => 'Templo Wong Tai Sin',
                'descricao_pt' => 'O Templo Wong Tai Sin é um templo taoísta em Shenzhen, China. É conhecido por suas previsões e é um dos templos mais populares da cidade.',
                'descricao_en' => 'Wong Tai Sin Temple is a Taoist temple in Shenzhen, China. It is known for its predictions and is one of the most popular temples in the city.',
                'descricao_es' => 'El Templo Wong Tai Sin es un templo taoísta en Shenzhen, China. Es conocido por sus predicciones y es uno de los templos más populares de la ciudad.',
            ],
            [
                'cidade' => 'Macau',
                'pais' => 'China',
                'categoria' => 'Cultural',
                'imagem_url' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'endereco' => 'Macau, China',
                'nome_pt' => 'Centro Histórico de Macau',
                'nome_en' => 'Historic Center of Macau',
                'nome_es' => 'Centro Histórico de Macau',
                'descricao_pt' => 'O Centro Histórico de Macau é o centro histórico da cidade de Macau, China. É um Patrimônio Mundial da UNESCO e um dos centros históricos mais importantes da Ásia.',
                'descricao_en' => 'The Historic Center of Macau is the historic center of the city of Macau, China. It is a UNESCO World Heritage Site and one of the most important historic centers in Asia.',
                'descricao_es' => 'El Centro Histórico de Macau es el centro histórico de la ciudad de Macau, China. Es un Sitio del Patrimonio Mundial de la UNESCO y uno de los centros históricos más importantes de Asia.',
            ],
        ];

        foreach ($attractions as $attraction) {
            // Verificar se já existe um ponto turístico com o mesmo nome
            $existing = TouristAttraction::where('nome_pt', $attraction['nome_pt'])
                ->orWhere('nome_en', $attraction['nome_en'])
                ->orWhere('nome_es', $attraction['nome_es'])
                ->first();
            
            if (!$existing) {
                TouristAttraction::create($attraction);
            }
        }
    }
}
