name: Deploy to KingHost

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Permite execução manual

jobs:
  deploy:
    runs-on: self-hosted # Usa o runner da KingHost
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Git pull
      run: |
        git pull origin main

    - name: Clear and cache configs
      run: |
        php artisan config:clear
        php artisan cache:clear
        php artisan route:clear
        php artisan view:clear
        
    - name: Cache optimizations
      run: |
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
        
    - name: Run migrations
      run: |
        php artisan migrate --force
        
    - name: Set permissions
      run: |
        chmod -R 755 storage bootstrap/cache
        chown -R www-data:www-data storage bootstrap/cache
        
    - name: Restart services
      run: |
        php artisan queue:restart
        sudo systemctl reload php8.2-fpm 2>/dev/null || true
        sudo systemctl reload nginx 2>/dev/null || true
        
    - name: Deploy completed
      run: |
        echo "✅ Deploy concluído com sucesso!"
        echo "🚀 Aplicação atualizada em $(date)"
